### PR TITLE
Optimization for 1.7.10

### PR DESCRIPTION
**Pull request by AnotherJavaCoder**
So I rewritten a big part of the mod, made optimizations. Hope that this will be usefull! :tada:

### CODE REVIEW

**Comment by TooPointOhh** [comment]
Me and WORMSTweaker will look through it. Thank you for your involvement with the mod.

**Comment by WORMSTweaker** [comment]
@AnotherJavaCoder Hum, emblems are a good idea, but also a bad one.
It's not my art, and also, it doesn't exist for non-popular Vocaloids.
So I won't add it to the mod, sorry :/

**Comment by AnotherJavaCoder** [comment]
It was just an idea I had in replacement for the discs. Because they are not just present in CreativeTabs removing them should be easy.

**Comment by WORMSTweaker** [comment]
@AnotherJavaCoder Removing emblems of disc? :/

**Comment by AnotherJavaCoder** [comment]
The emblems. The icon of the creative tab was a disc and I modified this to show a fake item that is the emblem.

**Comment by WORMSTweaker** [comment]
@AnotherJavaCoder Ho yeah, right >.<
In the newest version, the tab icon will be the item they're associated with (A leek for Miku, sake for Meiko, etc...). And the Main tab will have a Jukebox... OR maybe i'll use a Fake Item, to put something more appropriated :D

**Comment by TooPointOhh** [comment]
Arthur, do you have twitter by chance? I will try and set up a group for us to chat in, as it is better than chatting on a Pull Request...

**Comment by AnotherJavaCoder** [comment]
No I haven't... But I have Skype

**Comment by TooPointOhh** [comment]
Alright. Can you pm me your Skype account
On Jun 13, 2016 6:25 AM, Arthur TESSE <notifications@github.com> wrote:No I haven't... But I have Skype

**Comment by WORMSTweaker** [comment]
> Take this off. The mod is currently version 2.1 not 2.0.3

@AnotherJavaCoder is technically right, BUT, I think I'll reset the version number (Going back aaaaaall the way to 1.0!) because we made so much changes and optimizations...
It's almost not the same mod :0

**Comment by AnotherJavaCoder** [comment]
But I made the version number using your Readme and I recloned all my branch to be the same as yours to make the optimizations so it is the same mod but a little lighter with some additions that I can remove and put on a separated branch. Because it is yours you decide and I will follow

**Comment by WORMSTweaker** [comment]
@AnotherJavaCoder Do as you wish, my plan was to make a version per addon

**Comment by TooPointOhh** [comment]
Hey @WORMSTweaker have you released the SDK for the mod yet? I've not been
on GITHub for a while

**Comment by WORMSTweaker** [comment]
@TooPointOhh Nope, didn't worked on the mod this week, had to study :/
I'll work on it this week-end

**Comment by TooPointOhh** [comment]
oh... alright :P

**Pull request closed without merging**
